version: '3.8'
services:
  amqp-broker:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - server_default

  ocpp-db:
    image: citrineos/postgis:v1.1.0
    environment:
      POSTGRES_DB: citrine
      POSTGRES_USER: citrine
      POSTGRES_PASSWORD: citrine
    volumes:
      # - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citrine"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - server_default

  citrine:
    build:
      context: ../
      dockerfile: ./Server/deploy.Dockerfile
    volumes:
      - ../package.json:/usr/local/apps/citrineos/package.json:ro
      - ../package-lock.json:/usr/local/apps/citrineos/package-lock-host.json:ro
      - ../tsconfig.json:/usr/local/apps/citrineos/tsconfig.json:ro
      - ../tsconfig.build.json:/usr/local/apps/citrineos/tsconfig.build.json:ro
      - ../Server:/usr/local/apps/citrineos/Server:ro
      - ../00_Base:/usr/local/apps/citrineos/00_Base:ro
      - ../01_Data:/usr/local/apps/citrineos/01_Data:ro
      - ../02_Util:/usr/local/apps/citrineos/02_Util:ro
      - ../03_Modules/Certificates:/usr/local/apps/citrineos/03_Modules/Certificates:ro
      - ../03_Modules/Configuration:/usr/local/apps/citrineos/03_Modules/Configuration:ro
      - ../03_Modules/EVDriver:/usr/local/apps/citrineos/03_Modules/EVDriver:ro
      - ../03_Modules/Monitoring:/usr/local/apps/citrineos/03_Modules/Monitoring:ro
      - ../03_Modules/OcppRouter:/usr/local/apps/citrineos/03_Modules/OcppRouter:ro
      - ../03_Modules/Reporting:/usr/local/apps/citrineos/03_Modules/Reporting:ro
      - ../03_Modules/SmartCharging:/usr/local/apps/citrineos/03_Modules/SmartCharging:ro
      - ../03_Modules/Transactions:/usr/local/apps/citrineos/03_Modules/Transactions:ro
      - ./scripts:/usr/local/apps/citrineos/scripts
    environment:
      APP_NAME: 'all'
      APP_ENV: 'docker'
      SYNC_DB: 'true'
      CITRINEOS_UTIL_DIRECTUS_TOKEN: '-ssaT85n4S-wVD21LKOCDwvXN5PtnJc0'
      DATABASE_URL: postgres://citrine:citrine@ocpp-db:5432/citrine
    entrypoint: ["/usr/local/apps/citrineos/scripts/init-citrine.sh"]
    command: ["node", "/usr/local/apps/citrineos/Server/dist/index.js"]
    depends_on:
      ocpp-db:
        condition: service_healthy
      amqp-broker:
        condition: service_healthy
      directus:
        condition: service_healthy
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8085:8085
      - 8443:8443
      - 8444:8444
      - 9230:9229
    networks:
      - server_default

  directus:
    build:
      context: ../DirectusExtensions
      dockerfile: ./directus.Dockerfile
    ports:
      - 8055:8055
    volumes:
      - ./data/directus/uploads:/directus/uploads
      - ./directus-env-config.cjs:/directus/config.cjs
    depends_on:
      ocpp-db:
        condition: service_healthy
    environment:
      APP_NAME: 'all'
      KEY: '1234567890'
      SECRET: '0987654321'
      ADMIN_EMAIL: 'admin@citrineos.com'
      ADMIN_PASSWORD: 'CitrineOS!'
      CONFIG_PATH: '/directus/config.cjs'
      EXTENSIONS_AUTO_RELOAD: 'true'
      EXTENSIONS_CACHE_TTL: '1s'
      DB_CLIENT: 'pg'
      DB_HOST: ocpp-db
      DB_PORT: 5432
      DB_DATABASE: 'citrine'
      DB_USER: 'citrine'
      DB_PASSWORD: 'citrine'
      WEBSOCKETS_ENABLED: 'true'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8055/server/health || exit 1
      start_period: 15s
      interval: 15s
      timeout: 15s
      retries: 3
    networks:
      - server_default

volumes:
  pgdata:

networks:
  server_default:
    driver: bridge
