version: '3.9'

services:
  mqtt-server:
    image: eclipse-mosquitto:2.0.15
    ports:
      - "1883:1883"
    networks:
      - everest
      - server_server_default
    logging:
      driver: none

  nodered:
    image: ghcr.io/everest/everest-demo/nodered:0.0.23
    user: "1000:1000"
    ports:
      - "1881:1880"
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
      - FLOWS=/flows/flows.json
    volumes:
      - ./flows:/flows
    depends_on:
      - mqtt-server
    networks:
      - everest
      - server_server_default

  manager:
    image: ghcr.io/everest/everest-demo/manager:0.0.23
    platform: linux/x86_64
    ports:
      - "8888:8888"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1024mb'
    depends_on:
      - mqtt-server
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
      - EVEREST_TARGET_URL=ws://server-citrine-1:8081/cp001
    volumes:
      - ./config:/ext/source/config
      - ./logs:/tmp/everest_ocpp_logs
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - everest
      - server_server_default

networks:
  everest:
    name: everest
  server_server_default:
    external: true
